### ISSUE TITLE
EDP simulator generates NaN values in direct frequency

### ISSUE THREAD

**Issue by riemanli** [world-federation-of-advertisers/cross-media-measurement#1384]
**Describe the bug**
The [EDP simulator](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt) in this repo will generate NaN values in direct RF measurements when the sampled VIDs is empty.

**Component(s) affected**
Testing simulators

**Version**
v0.4.2

**Environment**
QA ("dev") environment

**Additional context**
When the EDP simulator [computes the RF from sampled VIDs](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c253dcd79af726be9d8bb3470d3409854ce98e7/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1294), if there is no any sample, the computation in [MeasurementResult.computeReachAndFrequency ](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c253dcd79af726be9d8bb3470d3409854ce98e7/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/MeasurementResults.kt#L39) will have value divided by 0.

**Comment by SanjayVas** [comment]
Is this fixed by #1389, or is there still more work here?
