### ISSUE TITLE
Duchy Mill Memory Leakage

### ISSUE THREAD

**Issue by renjiezh** [world-federation-of-advertisers/cross-media-measurement#1636]
**Describe the bug**
During the QA stress test, LLv2 mills crash periodical. According to the memory usage chart, memory leakage is likely to be the cause.
<img width="510" alt="Screenshot 2024-05-30 at 2 33 27 PM" src="https://github.com/world-federation-of-advertisers/cross-media-measurement/assets/94721804/45505076-2511-4765-b63c-78184eabce84">

**Steps to reproduce**
1. Launch multiple Measurements with large reach to keep mills busy.
2. Wait until crashes happen.

**Component(s) affected**
Duchy

**Version**
v0.5.5

**Environment**
halo-dev-qa

**Additional context**

**Comment by SanjayVas** [comment]
Closed by #1639
