### ISSUE TITLE
Kingdom could tolerate duplicated SetParticipantRequisitionParams request

### ISSUE THREAD

**Issue by renjiezh** [world-federation-of-advertisers/cross-media-measurement#1645]
**Describe the bug**
By nature of distributed system, when a mill successfully sends a request to the kingdom and the kingdom completes request, the mill might not be able to update its own state due to crash/restart. 

This happened for SetParticipantRequisitionParams rpc. Due to the kubernetes rollout, a mill completes the rpc but doesn't update the local state. After the cooldown time, the mill resend the request but receive an error that the state on the kingdom is not desired.

The kingdom could tolerate such case idempotently by reply success response without executing the request again. Specifically, when the kingdom receives a request for Measurement state A, if the state is actually the successor B, it directly reply with non-error response.

**Steps to reproduce**
Restart mill during stress test.

**Component(s) affected**
Kingdom, Duchy

**Version**
v0.5.5

**Environment**
halo-cmm-qa

**Additional context**

**Comment by renjiezh** [comment]
SetParticipantRequisitionParams also checks state of participant state. If the participant state is already the next state, it can be tolerated as well.

**Comment by SanjayVas** [comment]
This is bad design IMO.

**Comment by SanjayVas** [comment]
One way the caller can be smarter about this is to check whether the resource is already in the desired end state and skip the call. This can be aided by the use of etags. Pseudocode:

```kotlin
while (true) {
  val resource = readResource()
  if (alreadyInDesiredState(resource)) {
    break
  }
  try {
    mutateWithEtag(resource)
  } catch (e: StatusException) {
    if (e.status.code == ABORTED) {
      continue
    }
    throw e
  }
  break
}
```

**Comment by renjiezh** [comment]
This issue could also happen between duchies.

An extract explanation of this issue:

Suppose there are two parties A and B. They are either duchies or the kingdom. One of the stage transitions is like:
A is in stage A1, it launches an RPC to B to transit B1 to B2, then update itself to A2. 

There are at least 2 scenario that interruption causes permanent error.

Case 1: A updates B from B1 to B2 but A is interrupted at this moment so A is still A1. When A restart, it sends data again expecting B is in B1. However, B is already in B2 returning the error of state mismatch. This is regarded as permanent error.

Case 2: A updates B from B1 to B2 but A is interrupted at this moment so A is still A1(same as case 1). B starts to send data to A expecting A is in A2. However, A is still in A1 returning the error of state mismatch. This is regarded as permanent error.
