### ISSUE TITLE
Replace deprecated getRuntimePath() by using Runfiles

### ISSUE THREAD

**Issue by renjiezh** [world-federation-of-advertisers/cross-media-measurement#1749]
**Describe the bug**
`getRuntimePath()` is deprecated. It should be replaced by using Runfiles.getRuntimePath with Runfiles.preload().

**Steps to reproduce**
N/a

**Component(s) affected**
N/a

**Version**
v0.5.7

**Environment**
N/a

**Additional context**

**Comment by SanjayVas** [comment]
Duplicate of #1749
