### ISSUE TITLE
When submitting Reports with 100% video completion status filter for TV second by second data Reach value is showing same for both with and without Filter

### ISSUE THREAD

**Issue by nitamanna18** [world-federation-of-advertisers/cross-media-measurement#1827]
**Describe the bug**
When submitting Reports with 100% video completion status filter for TV second by second data Reach value is showing same for both with and without Filter.

Submitted a direct TV report in Staging to test TV second by second data, with the custom impression filters. 

Date range: 5th August to 18th August 2024
Metrics: All selected
Viewability: Not selected
Video completion: 100%

Report was submitted successfully, however, report output was returned as below,
Total Reach 1+ value = 1,265,000, and equal to the MRC and AMI results i.e. Output of Reach value is coming same for both with and without filter options.

Expected Result should be like below,

In AdvantEdge (TV reporting tool), the total Reach 1+ value was confirmed to be lower, = 1,021,000
AMI > MRC > custom (when custom 100%)

**RS definition:**
```
 {
            "name": "measurementConsumers/****/reportingSets/e5b4dc99b7ac4a2a9bba4b35aa40c1ca",
            "displayName": "P_CUSTOM_VIDEO_EDP_Linear",
            "filter": "video.completed_100_percent == true",
            "primitive": {
                "cmmsEventGroups": [
                    "dataProviders/*****/eventGroups/eTgg2pUC5sc",
                    "dataProviders/*****/eventGroups/SbYeLGr9FoI"
                ]
            }
        }
```

**RS definition:**
        {
```
            "name": "measurementConsumers/*****/reportingSets/e97f140f6c34f58a8b8498778d70f3d",
            "displayName": "P_AMI_VIDEO_EDP_Linear",
            "filter": "",
            "primitive": {
                "cmmsEventGroups": [
                    "dataProviders/*****/eventGroups/eTgg2pUC5sc",
                    "dataProviders/*****/eventGroups/SbYeLGr9FoI"
                ]
            }
        }
```

```
metricSpec": {
						"reach": {
							"privacyParams": {
								"delta": 1e-15,
								"epsilon": 0.000682
							}
						},
						"vidSamplingInterval": {
							"start": 0.0,
							"width": 1.0
						}
					},
					"metricResult": {
						"reach": {
							"value": "16762000"
						}
					},
					"timeInterval": {
						"endTime": "2024-08-18T00:00:00Z",
						"startTime": "2024-08-05T00:00:00Z"
					},
```

```
"timeIntervals": [
			{
				"endTime": "2024-08-18T00:00:00Z",
				"startTime": "2024-08-05T00:00:00Z"
			}
		]
```

```
"metricResult": {
"reach": {
"value": "1265000"}}
```

**Steps to reproduce**
as mentioned above

**Component(s) affected**
Halo v0.4.3 (Origin Staging Environment) during the TV second by Second Data testing

**Version**
Halo v.0.4.3

**Environment**
Origin Staging Environment.

**Additional context**
Not possible to reproduce in Production environment as we don't have TV second by second data.

**Comment by SanjayVas** [comment]
1. v0.4.x is unsupported.
2. Filtering is handled on the EDP end, not in any Halo component.
