### ISSUE TITLE
Reach-Frequency Variance in LLv2 measurements is being calculated as a negative value causing an error in report retrieval 

### ISSUE THREAD

**Issue by harrymeadows** [world-federation-of-advertisers/cross-media-measurement#1858]
**Describe the bug**

- Multi-EDP reports submitted in Origin Staging environment (Halo v0.5.8). 
- All direct and LLv2 requisitions are successfully fulfilled by EDPs. 
- All measurements appear to be successfully computed by the MPC consortium (according to Kingdom spanner)
- However, the report cannot be retrieved and remains 'in progress' in the Origin UI. 
- Following error is observed in reporting server logs:

- _Unable to get metric. Unable to compute variance of reach-frequency metric. The reach variance cannot be negative._ 

**Steps to reproduce**
1. Submit multi-EDP report (single media type) for a date range of your choice (report in question was 1 month)
2. Await completion

**Component(s) affected**
 Error logs identified in reporting server

**Version**
v0.5.8

**Environment**
Origin Staging env (Prod mirror)

**Additional context**
In Origin Production and Staging environments, the differential privacy params configuration files are following this Confluence page https://isbaorigin.atlassian.net/wiki/spaces/INT/pages/549290009/Privacy+Params#Origin-Production-Privacy-Params
 
The key difference is that:
In Production (v2.4) we have 2 configuration files. One for direct requisitions and one for LLv2 requisitions.
In Staging (v2.5) we only 1 configuration file, for both direct and LLv2 requisitions

**Comment by kungfucraig** [comment]
@harrymeadows can you provide the report definition here?

Meanwhile, @tristanvuong2021 is ensuring a single Metric variance computation failure doesn't fail the whole report. That will allow us to determine exactly which Metric is causing the problem.

@ple13 is looking into why we might be getting a negative variance. We think it may have something to do with a unique reach calculation, but seeing the report definition would allow us to refute this if there are no unique reach computations.

Will update here as we know more, and daily on slack.

**Comment by harrymeadows** [comment]
[report stg.json](https://github.com/user-attachments/files/17382341/report.stg.json)
@kungfucraig - report definition shared by Sergejs on slack is attached

**Comment by kungfucraig** [comment]
This was determined to be an EDP issue. However, error messages in the variance calculator have been improved.

**Comment by SanjayVas** [comment]
Error message improvement is in #1860
