### ISSUE TITLE
Measurements with MeasurementIndexShardId of -1 are not streamed to Herald

### ISSUE THREAD

**Issue by renjiezh** [world-federation-of-advertisers/cross-media-measurement#1862]
**Describe the bug**
Database column MeasurementIndexShardId is introduced by #1852. The default value is -1. Measurements of -1  are regarded as old entris and will be ignored in Streaming rpc call. However, the calculation (hash and mod) of MeasurementIndexShardId is possible to yield negative thus -1 is a valid value.

**Steps to reproduce**
Create a lot of Measurements and some of them has value of -1.

**Component(s) affected**
Kingdom, Duchy

**Version**
0.5.10-rc1

**Environment**
all envs

**Additional context**

**Comment by SanjayVas** [comment]
-1 shouldn't be possible. The shard ID is a hash mod 64.
