### ISSUE TITLE
Reporting Server Error logged as Info

### ISSUE THREAD

**Issue by mariolamassaavedra** [world-federation-of-advertisers/cross-media-measurement#1930]
**Describe the bug**
A specific error related to a failed precondition is being logged at info level rather than error 

**Steps to reproduce**
Unsure how to reproduce 

**Component(s) affected**
Reporting Server

**Version**
0.5.11

**Environment**
Origin Production

**Additional context**
![image](https://github.com/user-attachments/assets/c471b0c4-6593-48a1-bc6a-7115db1d1223)

**Comment by SanjayVas** [comment]
This is working as intended. FAILED_PRECONDITION is not an error on the server side. It's a client error, meaning the client did something incorrectly.
