### ISSUE TITLE
ListEventGroup API response is slow, when no CEL filter or keyword search results are found

### ISSUE THREAD

**Issue by nitamanna18** [world-federation-of-advertisers/cross-media-measurement#1941]
**Describe the bug**
When the ListEventGroup API cannot find results, the response time increases significantly, taking up to 54 seconds. However, when results are found, the API responds almost instantly (within milliseconds).
We made only one call from Origin Reports Adaptor (screenshot below) but we noticed 3 request to Kingdom log(screenshot below) for the same single request which returns the same result within 600 ms. 

Kingdom Log:
<img width="914" alt="image" src="https://github.com/user-attachments/assets/918d8a8b-3ee3-4020-b992-651789cbed84">

Origin Reports Adaptor Log
<img width="809" alt="image" src="https://github.com/user-attachments/assets/9274aa44-2585-4d4f-b91d-5cea667c9904">

**Steps to reproduce**
1. Login to Origin Platform 
2. Go to Campaign group page 
3. Search for Event Groups without any filters and the EGs not found in UI 
4. Click on “Search“ button to call listeventgroup API

**Component(s) affected**
Kingdom, Reporting Server

**Version**
Halo 5.11

**Environment**
Origin Stage & PROD Environment 

**Additional context**
attached log screenshot above.

**Comment by SanjayVas** [comment]
We made some performance enhancements to ListEventGroups in v0.5.13 as part of fixing a previous simulator issue. See #1923. Feel free to reopen if you still see the same problem after upgrading past that version.

As an aside, all issues filed here should be in the context of Halo software only. This means that the "Step to reproduce" should only cover parts of Halo. For the purposes of filing issues here, assume that the Origin UI doesn't exist.
