### ISSUE TITLE
Simulator created Event Groups are tagged with multiple Event templates 

### ISSUE THREAD

**Issue by nitamanna18** [world-federation-of-advertisers/cross-media-measurement#1961]
**Describe the bug**
While validating the [v0.5.14-rc1](https://urldefense.com/v3/__https://github.com/world-federation-of-advertisers/cross-media-measurement/releases/tag/[v0.5.14-rc1](https://urldefense.com/v3/__https:/github.com/world-federation-of-advertisers/cross-media-measurement/releases/tag/v0.5.14-rc1__;!!OrxsNty6D4my!8rwMti0uSk1lSKWQ5rVY0Tb3neqtEko8Tg9yX176mJ97iBqmAHGVhrly8LaW1ECFseuOcKigR6-rPE1BtUuaWL1CHR0$)__;!!OrxsNty6D4my!8rwMti0uSk1lSKWQ5rVY0Tb3neqtEko8Tg9yX176mJ97iBqmAHGVhrly8LaW1ECFseuOcKigR6-rPE1BtUuaWL1CHR0$) we notice that the EGs getting created by the Simulators are attached with multiple Event template. 

Each EG should only be associated with one media type and Common like, 
Common and Video or Common and Other or Common and Display
[downloaded-logs-20241210-133316.json](https://github.com/user-attachments/files/18080199/downloaded-logs-20241210-133316.json)

**Steps to reproduce**
1. call ListEG API and check the response in log  

**Component(s) affected**
Reporting Server

**Version**
v0.5.14-rc1

**Environment**
Origin DEV 

**Additional context**
Add any other context about the problem here. Please include any relevant captured logs/output (actual text preferred over screenshots of logs).

**Comment by SanjayVas** [comment]
This is working as intended. The simulator attaches all possible templates defined in the event message type on the EventGroups it creates.

Feel free to file a feature request if you'd like a way to specify the template(s) individually for each EventGroup.
