### ISSUE TITLE
Update grpc error codes in Kingdom Internal Services

### ISSUE THREAD

**Issue by uakyol** [world-federation-of-advertisers/cross-media-measurement#247]
Parent not found -> FAILED_PRECONDITION  and furthermore have PreconditionFailure set in the error details (see https://github.com/googleapis/api-common-protos/blob/37d5125da5c90f2124d15908a54a32ed3f470bc2/google/rpc/error_details.proto#L140)

self not found -> NOT_FOUND
some resource other than parent or self not found -> INVALID_ARGUMENT

**Comment by SanjayVas** [comment]
> some resource other than parent or self not found -> INVALID_ARGUMENT

I think this would still be FAILED_PRECONDITION. As per [Status codes and their use in gRPC](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md), INVALID_ARGUMENT is for when the arguments are incorrect regardless of the state of the system (e.g. some field is malformed or missing). In this case, the arguments could be correct if the entity with the given ID already existed. The fact that we don't allow user-specified IDs for creation is a separate matter.
