### ISSUE TITLE
Simple Report doesn't work with delta = 0.0

### ISSUE THREAD

**Issue by uakyol** [world-federation-of-advertisers/cross-media-measurement#595]
When SimpleReport create measurement is run with deltas = 0.0, get measurement returns null

**Comment by DimaMakarevich** [comment]
Command:
`/cross-media-measurement/bazel-bin/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport \
> --tls-cert-file=secretfiles/mc_tls.pem --tls-key-file=secretfiles/mc_tls.key \
> --cert-collection-file=secretfiles/kingdom_root.pem \
> --kingdom-public-api-target=kingdomv2.anapoc.comscore.com:8443 \
> --api-key=Bnc1DB9rdpU \
> create \
> --measurement-consumer=measurementConsumers/Cm3r3R9rcjg \
> --private-key-der-file=secretfiles/mc_cs_private.der  \
> --reach-and-frequency \
> --reach-privacy-epsilon=0.0033 \
> --reach-privacy-delta=0.0 \
> --frequency-privacy-epsilon=0.115 \
> --frequency-privacy-delta=0.0 \
> --vid-sampling-start=0.0 \
> --vid-sampling-width=1.0 \
> --measurement-ref-id=23 \
> --data-provider=dataProviders/X1jglh9reTE \
> --event-group=dataProviders/X1jglh9reTE/eventGroups/DeqznSO3UDI \
> --event-start-time=2021-03-01T05:00:00.000Z \
> --event-end-time=2021-04-06T05:00:00.000Z` 

Error:
![image](https://user-images.githubusercontent.com/43697527/172719498-b2eaacde-c56f-4cbe-b12c-5eec81db12be.png)

This error appears when delta values is specified 0.0
