### ISSUE TITLE
How to obtain a CLA?

### ISSUE THREAD

**Issue by mallman** [world-federation-of-advertisers/cross-media-measurement#65]
Hi. How do I obtain a CLA as per the contributing guidelines? It's not clear if I need one before I submit a PR.

Thanks!

**Comment by kungfucraig** [comment]
Hey Michael,

Thanks for the PR.  Are you with VideoAmp?

**Comment by mallman** [comment]
Yes.

**Comment by kungfucraig** [comment]
The CLA needs to be in place prior to the contribution being accepted. In your case, check with your management on CLA.

**Comment by mallman** [comment]
We're working on the CLA. Thank you.

**Comment by SanjayVas** [comment]
The current process is for the CLA to be done on a WFA partner organization basis rather than individual.
