### ISSUE TITLE
No ending reason set for computation

### ISSUE THREAD

**Issue by SanjayVas** [world-federation-of-advertisers/cross-media-measurement#677]
This was spotted in the logs of the Spanner computations server within the "worker2" Duchy on halo-cmm-dev.

```
WARNING: Stage attempt with primary key (-1008988325, liquid_legions_sketch_aggregation_v2: EXECUTION_PHASE_TWO, 6) did not have an ending reason set when ending computation, setting it to 'CANCELLED'.
```

Querying the ComputationStageAttempts table for that ComputationId results in the following:

<div _ngcontent-mbs-c268="" class="cfc-table-presenters" sandboxuid="0" style="box-sizing: border-box; border: 0px; font-family: Roboto, sans-serif; font-size: 12px; font-style: normal; font-weight: 400; margin: 0px; outline: 0px; padding: 0px; vertical-align: baseline; color: rgba(0, 0, 0, 0.87); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><cfc-table-columns-presenter _ngcontent-mbs-c268="" sandboxuid="0" style="box-sizing: border-box;"><div cfcstickyhorizontalscrollbaroverflowingelselector=".cfc-table-element" role="presentation" class="cfc-table-scroll-container" sandboxuid="0" jslog="54824;track:impression" style="box-sizing: border-box; border: 0px; font-family: inherit; font-size: 12px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; vertical-align: baseline; overflow: visible; min-height: 0px;"><div sandboxuid="0" style="box-sizing: border-box; border: 0px; font-family: inherit; font-size: 12px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; vertical-align: baseline;">

ComputationId | ComputationStage | Attempt | BeginTime | EndTime | Details | DetailsJSON |  
-- | -- | -- | -- | -- | -- | -- | --
-1008988325 | 1 | 1 | 2022-08-30T23:42:09.652017Z | 2022-08-30T23:42:11.454366Z | CAE= | {"reasonEnded":"SUCCEEDED"} |  
-1008988325 | 2 | 1 | 2022-08-30T23:42:11.454366Z | 2022-08-30T23:45:40.688327Z | CAE= | {"reasonEnded":"SUCCEEDED"} |  
-1008988325 | 3 | 1 | 2022-08-30T23:45:41.156663Z | 2022-08-30T23:45:42.171272Z | CAE= | {"reasonEnded":"SUCCEEDED"} |  
-1008988325 | 4 | 1 | 2022-08-30T23:45:42.171272Z | 2022-08-30T23:45:50.158201Z | CAE= | {"reasonEnded":"SUCCEEDED"} |  
-1008988325 | 6 | 1 | 2022-08-30T23:45:50.753601Z | 2022-08-30T23:45:55.385577Z | CAE= | {"reasonEnded":"SUCCEEDED"} |  
-1008988325 | 7 | 1 | 2022-08-30T23:45:55.385577Z | 2022-08-30T23:46:27.052964Z | CAE= | {"reasonEnded":"SUCCEEDED"} |  
-1008988325 | 8 | 1 | 2022-08-30T23:46:27.477582Z | 2022-08-30T23:47:03.349957Z | CAE= | {"reasonEnded":"SUCCEEDED"} |  
-1008988325 | 9 | 1 | 2022-08-30T23:47:03.349957Z | 2022-08-30T23:48:52.269688Z | CAE= | {"reasonEnded":"SUCCEEDED"} |  
-1008988325 | 10 | 1 | 2022-08-30T23:48:53.053464Z | 2022-08-30T23:55:26.668691Z | CAM= | {"reasonEnded":"LOCK_OVERWRITTEN"} |  
-1008988325 | 10 | 2 | 2022-08-30T23:55:26.668691Z | 2022-08-31T00:05:04.430031Z | CAQ= | {"reasonEnded":"CANCELLED"} |  
-1008988325 | 10 | 3 | 2022-08-30T23:56:57.478655Z | 2022-08-31T00:05:04.430031Z | CAQ= | {"reasonEnded":"CANCELLED"} |  
-1008988325 | 10 | 4 | 2022-08-30T23:57:12.992429Z | 2022-08-31T00:05:04.430031Z | CAQ= | {"reasonEnded":"CANCELLED"} |  
-1008988325 | 10 | 5 | 2022-08-30T23:57:41.693306Z | 2022-08-31T00:05:04.430031Z | CAQ= | {"reasonEnded":"CANCELLED"} |  
-1008988325 | 10 | 6 | 2022-08-30T23:58:20.300635Z | 2022-08-31T00:05:04.430031Z | CAQ= | {"reasonEnded":"CANCELLED"} |  
-1008988325 | 10 | 7 | 2022-08-31T00:00:21.112744Z | 2022-08-31T00:00:27.892296Z | CAE= | {"reasonEnded":"SUCCEEDED"} |  
-1008988325 | 11 | 1 | 2022-08-31T00:00:27.892296Z | 2022-08-31T00:04:17.380198Z | CAE= | {"reasonEnded":"SUCCEEDED"} |  
-1008988325 | 12 | 1 | 2022-08-31T00:04:28.110317Z | 2022-08-31T00:05:04.430031Z | CAE= | {"reasonEnded":"SUCCEEDED"} |  

</div><div tabindex="0" class="cfc-table-last-focusable" sandboxuid="0" style="box-sizing: border-box; border: 0px; font-family: inherit; font-size: 12px; font-style: inherit; font-weight: inherit; margin: 0px; outline: 0px; padding: 0px; vertical-align: baseline;"></div></div></cfc-table-columns-presenter></div><cfc-table-pagination _ngcontent-mbs-c268="" class="cfc-md1 ng-star-inserted" _nghost-mbs-c265="" sandboxuid="0" jslog="54825" style="box-sizing: border-box; display: block; overflow: hidden; width: 2240px; background-image: inherit; background-position: inherit; background-size: inherit; background-repeat: inherit; background-attachment: inherit; background-origin: inherit; background-clip: inherit; background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.87); font-family: Roboto, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">

Querying the Computations table gave the following for ComputationDetailsJson (prettified using `jq`):

```json
{
  "blobsStoragePrefix": "computation-blob-storage/Ih4-Qg7iAys",
  "endingState": "SUCCEEDED",
  "kingdomComputation": {
    "publicApiVersion": "v2alpha",
    "measurementSpec": "CuoBCAES5QEIrfyPlQUS3AEKzwEKPXR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmNyeXB0by50aW5rLkVjaWVzQWVhZEhrZGZQdWJsaWNLZXkSiwESRAoECAIQAxI6EjgKMHR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmNyeXB0by50aW5rLkFlc0djbUtleRICEBAYARgBGiEA2VOaFS7y+xGQvC2VydELNZValk7ASE8EXHny7b0tOX4iIC1a/MlmcWmzimHAUyPjtZfuRLqtlS6qUdkLj8/eb15bGAMQARit/I+VBSABEiAK2jUhaG3CB4sA8IS1t582X7x2aWCdOEr4+lqjqBkDJRIgVi/udYPVVK3ocMFYIggJTC21hMdelowv9jyFiLV79LoSINTgsqFF0GJjrqzzpp+8kdOHgijNPPYLNqdoY9uMZCO3EiDUJg7UQQgGifrpLCazfG5sQTFCv1ckAGxY+3ThDCvjDhIgLjlj+A1Nd/4SfKninOX/2pv4mJkf3/x0lcwcAxIXu+kSILCgiiq0Lb1tNvVCFl5rAMzMYfqzOb8AmbUBN9NAttPfGgUVAACAPyIoChIJmpmZmZmZuT8Rje21oPfGsD4SEgmamZmZmZm5PxGN7bWg98awPg==",
    "measurementPublicKey": {
      "format": "TINK_KEYSET",
      "data": "CK38j5UFEtwBCs8BCj10eXBlLmdvb2dsZWFwaXMuY29tL2dvb2dsZS5jcnlwdG8udGluay5FY2llc0FlYWRIa2RmUHVibGljS2V5EosBEkQKBAgCEAMSOhI4CjB0eXBlLmdvb2dsZWFwaXMuY29tL2dvb2dsZS5jcnlwdG8udGluay5BZXNHY21LZXkSAhAQGAEYARohANlTmhUu8vsRkLwtlcnRCzWVWpZOwEhPBFx58u29LTl+IiAtWvzJZnFps4phwFMj47WX7kS6rZUuqlHZC4/P3m9eWxgDEAEYrfyPlQUgAQ=="
    }
  },
  "liquidLegionsV2": {
    "role": "NON_AGGREGATOR",
    "parameters": {
      "maximumFrequency": 10,
      "liquidLegionsSketch": {
        "decayRate": 12,
        "size": "100000"
      },
      "noise": {
        "reachNoiseConfig": {
          "blindHistogramNoise": {
            "epsilon": 1,
            "delta": 1
          },
          "noiseForPublisherNoise": {
            "epsilon": 1,
            "delta": 1
          },
          "globalReachDpNoise": {
            "epsilon": 0.1,
            "delta": 1e-06
          }
        },
        "frequencyNoiseConfig": {
          "epsilon": 0.1,
          "delta": 1e-06
        }
      },
      "ellipticCurveId": 415
    },
    "participant": [
      {
        "duchyId": "worker2",
        "publicKey": {
          "generator": "A2sX0fLhLEJH+Lzm5WOkQPJ3A32BLeszoPShOUXYmMKW",
          "element": "Axql5u/MneZ+Me25qE06TKoKDNF3Get5XxtdcIHivzF1"
        },
        "elGamalPublicKey": "EiEDaxfR8uEsQkf4vOblY6RA8ncDfYEt6zOg9KE5RdiYwpYaIQMapebvzJ3mfjHtuahNOkyqCgzRdxnreV8bXXCB4r8xdQ==",
        "elGamalPublicKeySignature": "MEUCIDORmvsjh07/tUI4HrGmONRElUpRThijtBO837moHe8hAiEA8b0mAhLuhkqhYbjmkbJvOr2rBaYSmnzzT78fHQEgSqE=",
        "duchyCertificateDer": "MIIB5TCCAYugAwIBAgIUD78MTB4sT79XxdvNwvBr/qHA5OowCgYIKoZIzj0EAwIwLDEVMBMGA1UECgwMSGFsbyBDTU0gRGV2MRMwEQYDVQQDDApXb3JrZXIyIENBMB4XDTIyMDcyOTE4MTMzOVoXDTMyMDcyNjE4MTMzOVowKTEVMBMGA1UECgwMSGFsbyBDTU0gRGV2MRAwDgYDVQQDDAdXb3JrZXIyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAENwAOHu7k/lpUwdQe0y904QkD0JIvpfty8Sjo9IXVLjq53wqO7bSgmDIt2QYebVThciOd4UKC8doi7xFQXciimKOBjTCBijAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFK9pSQh8B6Q598dGOpiTvvUl16O7MB0GA1UdDgQWBBQPQhRN905ulZIoJnHJNyscGulbXTALBgNVHQ8EBAMCBeAwMAYDVR0RBCkwJ4IaKi53b3JrZXIyLmRldi5oYWxvLWNtbS5vcmeCCWxvY2FsaG9zdDAKBggqhkjOPQQDAgNIADBFAiEA15agdGryz+9x7uouhDw/Zf2C/xnOUo9OVbQ53EDvdK8CIGpl7DEzpIYItGAGPFBltA5gEepfpL88OrAdZHF8bod3"
      },
      {
        "duchyId": "worker1",
        "publicKey": {
          "generator": "A2sX0fLhLEJH+Lzm5WOkQPJ3A32BLeszoPShOUXYmMKW",
          "element": "Az6TDc5eiEUB6K7GH1OEqObinexiepQzy//kVxgz31zj"
        },
        "elGamalPublicKey": "EiEDaxfR8uEsQkf4vOblY6RA8ncDfYEt6zOg9KE5RdiYwpYaIQM+kw3OXohFAeiuxh9ThKjm4p3sYnqUM8v/5FcYM99c4w==",
        "elGamalPublicKeySignature": "MEYCIQDzMqDqV1bBhpvZ2sRsozrkpK3bVPtdcwq15/DYaAmLeAIhAIa2zmT9xTl0Gs/0wj/sELa62cu/9ONcvH/ykNugZ6Kd",
        "duchyCertificateDer": "MIIB5TCCAYugAwIBAgIUPYEx9H1BSNg7BAxMpgKP8f6akPAwCgYIKoZIzj0EAwIwLDEVMBMGA1UECgwMSGFsbyBDTU0gRGV2MRMwEQYDVQQDDApXb3JrZXIxIENBMB4XDTIyMDcyOTE4MTUwNFoXDTMyMDcyNjE4MTUwNFowKTEVMBMGA1UECgwMSGFsbyBDTU0gRGV2MRAwDgYDVQQDDAdXb3JrZXIxMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEe5z8YtYYtKimvGRnOwpnxZQS2WLepJ/MW9M5AXp79Wg0f2ppOXvXPncuw6ECJDbI034avjfOJLXUF5Zx8SltU6OBjTCBijAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFBBZC7JmE03G1c74SRXJ11Y1eaLpMB0GA1UdDgQWBBRphWYwUOESM+daAXNc+yy4XV3oOjALBgNVHQ8EBAMCBeAwMAYDVR0RBCkwJ4IaKi53b3JrZXIxLmRldi5oYWxvLWNtbS5vcmeCCWxvY2FsaG9zdDAKBggqhkjOPQQDAgNIADBFAiEAnem13Lo79Nc36ur5U37JoGTULVbZmWwPjklUn+sZPyMCIFe8PWzymm1NJbG/42iMTBs1d9e2Eg/TVM1OB9L1sXtV"
      },
      {
        "duchyId": "aggregator",
        "publicKey": {
          "generator": "A2sX0fLhLEJH+Lzm5WOkQPJ3A32BLeszoPShOUXYmMKW",
          "element": "A20YcYJacmlE1rWcZWiC7HTi8AUIZzSS1jXBY295j3q4"
        },
        "elGamalPublicKey": "EiEDaxfR8uEsQkf4vOblY6RA8ncDfYEt6zOg9KE5RdiYwpYaIQNtGHGCWnJpRNa1nGVogux04vAFCGc0ktY1wWNveY96uA==",
        "elGamalPublicKeySignature": "MEUCIQC7IaNLHAFOcrEzPQhlfoQTDxWzgKzw0Z08duSPAZ4/+wIgVfTemiYP62WPp4LaLeNCxsd2acma5J6UoeKalqF/+Dc=",
        "duchyCertificateDer": "MIIB7TCCAZSgAwIBAgIUMWePkRD78fxf7XR/FJRI+99c8kYwCgYIKoZIzj0EAwIwLzEVMBMGA1UECgwMSGFsbyBDTU0gRGV2MRYwFAYDVQQDDA1BZ2dyZWdhdG9yIENBMB4XDTIyMDcyOTE4MTgzN1oXDTMyMDcyNjE4MTgzN1owLDEVMBMGA1UECgwMSGFsbyBDTU0gRGV2MRMwEQYDVQQDDApBZ2dyZWdhdG9yMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4Pt+OVbT1ne1+jHHKKMEwYwAA8oHf2wCsl7x8G5LoSQqvVR8V8JKJUNOA5i4z5jBWHGt/1TAZ8A7iYROuZZiFaOBkDCBjTAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFEetV5EszT17lLVF0r4f7V52atw5MB0GA1UdDgQWBBRYH+y724vCS2A9KdGUevcPWIwtrTALBgNVHQ8EBAMCBeAwMwYDVR0RBCwwKoIdKi5hZ2dyZWdhdG9yLmRldi5oYWxvLWNtbS5vcmeCCWxvY2FsaG9zdDAKBggqhkjOPQQDAgNHADBEAiA44QCvuMHdmYMq5ROUmPA5XnxWKtbX3bl+Wb8mMCL3mQIgQJGcGkMPOqy274MNK8DTlNLqyVNO0IDdQVSgpaE8WZQ="
      }
    ],
    "combinedPublicKey": {
      "generator": "A2sX0fLhLEJH+Lzm5WOkQPJ3A32BLeszoPShOUXYmMKW",
      "element": "A8leFaNR9+Vw/NUfBkGksb4di3Wb0pTeGP1Zg2uVgN+B"
    },
    "partiallyCombinedPublicKey": {
      "generator": "A2sX0fLhLEJH+Lzm5WOkQPJ3A32BLeszoPShOUXYmMKW",
      "element": "AlyNNsjQuLnaDAEx62NGjOKKdmyd7VnSd4ewrcJ/0DcA"
    },
    "localElgamalKey": {
      "secretKey": "osvxlSP1mb8apAAH991QndvgVm/ZbjPnfJGQ53bOm30=",
      "publicKey": {
        "generator": "A2sX0fLhLEJH+Lzm5WOkQPJ3A32BLeszoPShOUXYmMKW",
        "element": "Axql5u/MneZ+Me25qE06TKoKDNF3Get5XxtdcIHivzF1"
      }
    }
  }
}
```

**Comment by SanjayVas** [comment]
The Computations table gave a GlobalComputationId of `Ih4-Qg7iAys`. This decodes to an ExternalComputationId of 2458470900029326123 at the Kingdom. The Measurement state there is listed as 5 (SUCCEEDED).

**Comment by SanjayVas** [comment]
Was enabling metrics and now correctness test is failing on halo-cmm-dev. Seeing a bunch more of these "did not have an ending reason set when ending computation, setting it to 'CANCELLED'" messages in  aggregator-spanner-computations-server-deployment.

**Comment by renjiezh** [comment]
Not producible in QA env.
