### ISSUE TITLE
Base64 decoding error from Reporting ListReports and GetReport

### ISSUE THREAD

**Issue by mariolamassaavedra** [world-federation-of-advertisers/cross-media-measurement#758]
-When a report is created through the rpeorting server, when calling the listReports or getReport API the server returns error UNKNOWN. 
- Following the Error to the kingdom we can see IOException-Illegal base64 character ""-1”
- A [fix](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/743) was done but the UNKNOWN error is still present
- We were able to replicate this behaviour using Halo's dev environment

**Comment by SanjayVas** [comment]
@mariolamassaavedra Note that #743 only fixes new Measurements. All existing Measurements created by the Reporting server prior to this fix are effectively broken and need to be deleted or else they will trigger the same error. Did you already delete all of these Measurements and their associated Reports?

If you already did that, can you indicate which version of the Reporting server and Kingdom that you encountered this? i.e. which commit they were deployed at. See the pending PR for the bug template at #757.

**Comment by tristanvuong2021** [comment]
This pull request I just linked is related to this. The bug doesn't cause every list/get to fail, but does cause some to fail.

**Comment by SanjayVas** [comment]
So to clarify, #743 was an incomplete fix and #770 should resolve the issue (assuming Reports created before #743 have been deleted).

**Comment by mariolamassaavedra** [comment]
We redeployed everything using d85919b12bc389f57797ecb7a06921fbe69371f0, got new MC and EDP ids with no previous reports. Successfully created a event groups, reporting sets and reports. We were able to successfully call get/list reports and saw the expected response. 

After about an hour we tried to list/get reports again and got error UNKNOWN from the reporting server. I've checked the Kingdom logs but can't see any error there. I see a few lines with : "Dec 07, 2022 5:50:11 PM wfa.measurement.api.v2alpha.Measurements GetMeasurement" 

And towards the end "INFO: [pool-2-thread-1] gRPC 68510 complete"

Seems like the error is a different one now, I'm happy to close this bug and open a new one with the new details.

**Comment by SanjayVas** [comment]
This bug is already closed. Please file a new one if you see a new error, or reopen this one if you see the same error.

You'll want to find the stack trace that matches up with the UNKNOWN error in the Reporting server logs. It should be set up to log stack traces for all UNKNOWN and INTERNAL errors.
