### ISSUE TITLE
Using periodic time interval in Report with increment but no value results in ALREADY_EXISTS error

### ISSUE THREAD

**Issue by mariolamassaavedra** [world-federation-of-advertisers/cross-media-measurement#759]
"- Passing the expected variables to the createReport Error returns INVALID_ARGUMENT the first time the call is done and ALREADY_EXISTS if the payload is reused. Sample payload has been shared with Halo team
- When passing a blank value on the peridic time interval object the reporting server returns ALREADY_EXISTS , this might be related to the point above. Halo was able to replicate and a PR has been opened to investigate the issue"

**Comment by SanjayVas** [comment]
> Halo was able to replicate and a PR has been opened to investigate the issue

@tristanvuong2021 is this part correct? Can you link the PR here?

**Comment by SanjayVas** [comment]
Ah, I think the ALREADY_EXISTS error is what was reproduced but not the INVALID_ARGUMENT. I'm going to split these up into separate issues.
