### ISSUE TITLE
UNKNOWN status code sometimes returned from RPCs where there would be a more appropriate status code

### ISSUE THREAD

**Issue by mariolamassaavedra** [world-federation-of-advertisers/cross-media-measurement#761]
- Various methods return UNKNOWN instead of a more meaningful message
- This causes delays as the team needs to go through Halo’s code and analyse the process to try to understand what the error is so we can report back

**Comment by TNATALI** [comment]
@mariolamassaavedra would you have a list of 'methods' or instances when you encountered the error message to return as 'UNKNOWN' This will help the Engg team better understand the Issue.

**Comment by SanjayVas** [comment]
Please file these with specific method calls/conditions where a different status code would have been more appropriate. See the list of status codes and their descriptions here: https://grpc.github.io/grpc/core/md_doc_statuscodes.html.

**Comment by SanjayVas** [comment]
Closing this as each case should be filed as a separate issue.

**Comment by mariolamassaavedra** [comment]
Agree with the request above. Will collate the specific methods and adhere to the defined template.
