### ISSUE TITLE
Add certificate/key rotation guide and explainer

### ISSUE THREAD

**Issue by mariolamassaavedra** [world-federation-of-advertisers/cross-media-measurement#764]
- There is no documented process on how to rotate certificates which has blocked the team from executing integration tasks
- Work around is to create new resources which causes delay and rework
- Halo has provided some help to aide with the knowledge gap but after following instructions there is still unexpected results which might imply there is a bug in the code
- Further analysis is required

**Comment by SanjayVas** [comment]
> Halo has provided some help to aide with the knowledge gap but after following instructions there is still unexpected results which might imply there is a bug in the code

These should be looked at individually.

Documenting the certificate rotation process more explicitly is something that is work that is currently planned. All of the information is currently available (e.g. deployment guides indicate where certificates are referenced in configuration, API messages reference which certificates are used), but not synthesized into one place.
