### ISSUE TITLE
Using periodic time interval in Report with increment and value set sometimes results in INVALID_ARGUMENT

### ISSUE THREAD

**Issue by SanjayVas** [world-federation-of-advertisers/cross-media-measurement#769]
Reported by @mariolamassaavedra on behalf of Amritha Shenoy from Slack thread https://cross-mediaworkspace.slack.com/archives/C0312M4HE3F/p1668180627736149. Related to #759.

Not yet reproducible by Halo eng.

**Comment by tristanvuong2021** [comment]
I have been able to reproduce it. The issue is when cumulative is set to true.
