### ISSUE TITLE
Decryption failure in Reporting ListEventGroups

### ISSUE THREAD

**Issue by SanjayVas** [world-federation-of-advertisers/cross-media-measurement#781]
Split out from https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/760#issuecomment-1341302750, reported by @mariolamassaavedra 

**Describe the bug**
When listing event groups via the reporting server for a specific MC and EDP the response is an `UNKNOWN` error. Logs show a `GeneralSecurityException` for decryption failure.

**Steps to reproduce**
Preconditions:
1. MC and EDP exist in the Kingdom and configured with their certificates and keys
2. Event groups with encrypted meta data exist for the MC/EDP combination

How to reproduce
1. Call the listEventGroups Method through the reporting server as the MC

Sample call:
grpcurl -key certs/halo/mc_tls.key -cert certs/halo/mc_tls.pem -cacert certs/halo/reporting_root.pem -import-path protos -import-path protos/Reporting -proto event_groups_service.proto -d '{"parent":"measurementConsumers/VCTqwV_vFXw/dataProviders/R180F6AQ584"}' v1alpha.reporting.dev.halo-cmm.org:8443 wfa.measurement.reporting.v1alpha.EventGroups/ListEventGroups 

**Component(s) affected**
Reporting Server

**Version**
d85919b12bc389f57797ecb7a06921fbe69371f0

**Environment**
ISBA's Dev environment

**Additional context**
In the local origin set up we are using Halo's provided tink files to set up the EDP and MC, the metadata for the event groups is being encrypted with he MC;s public tink and the reporting server has access to the correct MC private tink

Stack trace from logs:
```
java.security.GeneralSecurityException: decryption failed at com.google.crypto.tink.hybrid.HybridDecryptWrapper$WrappedHybridDecrypt.decrypt(HybridDecryptWrapper.java:73) at org.wfanet.measurement.common.crypto.tink.TinkPrivateKeyHandle.hybridDecrypt(KeyHandle.kt:77) at org.wfanet.measurement.common.crypto.PrivateKeyHandle$DefaultImpls.hybridDecrypt$default(KeyHandle.kt:28) at org.wfanet.measurement.consent.client.measurementconsumer.MeasurementConsumerClientKt.decryptMetadata(MeasurementConsumerClient.kt:128) at org.wfanet.measurement.reporting.service.api.v1alpha.EventGroupsService.listEventGroups(EventGroupsService.kt:94) at org.wfanet.measurement.reporting.service.api.v1alpha.EventGroupsService$listEventGroups$1.invokeSuspend(EventGroupsService.kt) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

Event groups:

```json
{

  "eventGroups": [

    {

      "name": "dataProviders/MNstouxIrrI/eventGroups/C8ZbWOzPJfE",

      "measurementConsumer": "measurementConsumers/Pk21bxO3Uxc",

      "measurementConsumerCertificate": "measurementConsumers/Pk21bxO3Uxc/certificates/Gpl9qhO3U4g",

      "measurementConsumerPublicKey": {

        "data": "CAES5QEIrfyPlQUS3AEKzwEKPXR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmNyeXB0by50aW5rLkVjaWVzQWVhZEhrZGZQdWJsaWNLZXkSiwESRAoECAIQAxI6EjgKMHR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmNyeXB0by50aW5rLkFlc0djbUtleRICEBAYARgBGiEA2VOaFS7y+xGQvC2VydELNZValk7ASE8EXHny7b0tOX4iIC1a/MlmcWmzimHAUyPjtZfuRLqtlS6qUdkLj8/eb15bGAMQARit/I+VBSAB",

        "signature": "MEUCIQDP7cgMqAuP3va5QRbLDatJe69yVpg+H4S5EKYMR8X4aQIgHxH5vAfvwFVSfS9nvvmzKF99o5mgiDWjBwPyihFeWGk="

      },

      "eventGroupReferenceId": "TestEvent1"

    },

    {

      "name": "dataProviders/MNstouxIrrI/eventGroups/KN2jfuzPYw8",

      "measurementConsumer": "measurementConsumers/Pk21bxO3Uxc",

      "measurementConsumerCertificate": "measurementConsumers/Pk21bxO3Uxc/certificates/Gpl9qhO3U4g",

      "measurementConsumerPublicKey": {

        "data": "CAES5QEIrfyPlQUS3AEKzwEKPXR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmNyeXB0by50aW5rLkVjaWVzQWVhZEhrZGZQdWJsaWNLZXkSiwESRAoECAIQAxI6EjgKMHR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmNyeXB0by50aW5rLkFlc0djbUtleRICEBAYARgBGiEA2VOaFS7y+xGQvC2VydELNZValk7ASE8EXHny7b0tOX4iIC1a/MlmcWmzimHAUyPjtZfuRLqtlS6qUdkLj8/eb15bGAMQARit/I+VBSAB",

        "signature": "MEUCIQDP7cgMqAuP3va5QRbLDatJe69yVpg+H4S5EKYMR8X4aQIgHxH5vAfvwFVSfS9nvvmzKF99o5mgiDWjBwPyihFeWGk="

      },

      "eventGroupReferenceId": "TestEvent2"

    },

    {

      "name": "dataProviders/MNstouxIrrI/eventGroups/RPK29BOmsGI",

      "measurementConsumer": "measurementConsumers/Pk21bxO3Uxc",

      "eventGroupReferenceId": "001",

      "eventTemplates": [

        {

          "type": "wfa.measurement.api.v2alpha.event_templates.testing.TestVideoTemplate"

        }

      ]

    }

  ]

}
```

**Comment by SanjayVas** [comment]
So it looks like we have a [unit test](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt) that covers metadata decryption, but it's using a directly-populated `InMemoryEncryptionKeyPairStore`. I'm therefore guessing if there's a bug, it's in `EncryptionKeyPairMap` and how it loads the key pairs from the config file.

**Comment by SanjayVas** [comment]
This error should also probably use status code `FAILED_PRECONDITION` indicating that the EventGroup metadata is not decryptable. It means that the EventGroup data was either incorrectly encrypted or that the Reporting server is trying to use the wrong decryption key.

**Comment by SanjayVas** [comment]
@mariolamassaavedra I don't see the `encrypted_metadata` field set in any of the EventGroups you've provided. I was going to see if I could decrypt it manually as you said you used the testing key in the repo. This would help determine whether the encryption was done correctly as opposed to it being an issue with the decryption key.

**Comment by mariolamassaavedra** [comment]
You are right we used the wrong payload apologies for that. I tried listing the event group you created in the Halo dev environment and get unknown. I don't think I have access to the logs to help you gather them but here's the api call and response:

grpcurl -key certs/halo/mc_tls.key -cert certs/halo/mc_tls.pem -cacert certs/halo/reporting_root.pem -import-path protos -import-path protos/Reporting -proto event_groups_service.proto -d '{"parent":"measurementConsumers/VCTqwV_vFXw/dataProviders/FeQ5FqAQ5_0"}' v1alpha.reporting.dev.halo-cmm.org:8443 wfa.measurement.reporting.v1alpha.EventGroups/ListEventGroups
ERROR:
  Code: Unknown
  Message:

**Comment by SanjayVas** [comment]
I need to first delete any event groups that don't have encrypted metadata to not fall afoul of #783, as that's not yet fixed.

**Comment by SanjayVas** [comment]
Closing this as not reproducible. After deleting all other EventGroups for `dataProviders/FeQ5FqAQ5_0`, I was able to successfully call ListEventGroups using the Reporting tool. I suspect the issue is that the metadata was not encrypted correctly. I have some in-progress work for #768 that will demonstrate how to encrypt correctly in the EDP simulator, but there's also already an example in [EventGroupsServiceTest](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt)

```shell
bazel-bin/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting --tls-cert-file=src/main/k8s/testing/secretfiles/mc_tls.pem   --tls-key-file=src/main/k8s/testing/secretfiles/mc_tls.key   --cert-collection-file src/main/k8s/testing/secretfiles/reporting_root.pem   --reporting-server-api-target v1alpha.reporting.dev.halo-cmm.org:8443 event-groups list --parent=measurementConsumers/VCTqwV_vFXw/dataProviders/FeQ5FqAQ5_0
```

Output:
```textproto
event_groups {
  name: "measurementConsumers/VCTqwV_vFXw/dataProviders/FeQ5FqAQ5_0/eventGroups/Wmfy7BB1W38"
  data_provider: "dataProviders/FeQ5FqAQ5_0"
  event_group_reference_id: "001-edp1"
  event_templates {
    type: "wfa.measurement.api.v2alpha.event_templates.testing.TestVideoTemplate"
  }
  metadata {
    event_group_metadata_descriptor: "dataProviders/FeQ5FqAQ5_0/eventGroupMetadataDescriptors/AnBj8RB1XFc"
    metadata {
      type_url: "type.googleapis.com/wfa.measurement.api.v2alpha.event_group_metadata.testing.TestMetadataMessage"
      value: "\n\n\n\bJohn Doe"
    }
  }
}
```

**Comment by SanjayVas** [comment]
Demonstration of metadata encryption in EDP simulator: #786
