### ISSUE TITLE
getReport fails when report status is different from Running

### ISSUE THREAD

**Issue by mariolamassaavedra** [world-federation-of-advertisers/cross-media-measurement#782]
**Describe the bug**
Calling getReport works when the report status = Running, after the measurements/requisitions have been completed the call returns UNKNOWN with no visible errors in the kingdom. 

**Steps to reproduce**
1. Create a report through the reporting server and ensure EDP simulators are running
2. Immediately call getReport - the report shows as RUNNING
3. Wait a few minutes to allow for the measurements/requisitions to be fulfilled
4. cal getReport - the response is UNKNOWN 

**Component(s) affected**
Reporting Server

**Version**
d85919b12bc389f57797ecb7a06921fbe69371f0

**Environment**
Origin's dev environment

**Additional context**
No errors are seen on the kingdom logs. I can see the getMeasurement calls being received by the kingdom and their status. I see some are ready: 

encrypted_result: "\001R\243\376-\004\275m9\364)\036^\017$\321\340\304\251\vt\337\362\017@b-S\227\225D\331\177\335x\a\206\231\365\027\004\r\246\220CX\211\333\261LvC\250\263\223I\265?@|\241W\302]\324\262\276FyW\261\323p\017\204\370\a(\263\263c!\263\377\247\b4\257\244\271r\212\213p\365\250\351\325SI"

Some others have requisitions in status: measurement_states: PENDING_REQUISITION_PARAMS and measurement_states: PENDING_REQUISITION_FULFILLMENT 

But no evident error of anything failing in the Kingdom

**Comment by SanjayVas** [comment]
Need more info to debug. If there's an UNKNOWN error returned to the client, then there should be a matching log entry in the server. Please include the stack trace of the error from the Reporting API server. If that server shows that the error was caused by an RPC to another backend (e.g. the internal Reporting server), then include the logs from there too.

**Comment by mariolamassaavedra** [comment]
Update - after deploying some of the latest fixes this error is no longer occurring and we are able to retrieve reports when running or complete. Will mark as closed
