### ISSUE TITLE
The certificate which we used while creating an eventGroup is not showing the same in listEventGroups results.

### ISSUE THREAD

**Issue by dprao88** [world-federation-of-advertisers/cross-media-measurement#813]
**Describe the bug**
The certificate which we used while creating an eventGroup, is not showing the same in listEventGroups results.

**Steps to reproduce**
1. Create an event Group with new certificate 
<img width="956" alt="image" src="https://user-images.githubusercontent.com/122367168/212649594-7ca634dc-4c63-4d74-bf6c-b053bca50f61.png">

2. Check the certificate in ListEventGroups result. 
<img width="904" alt="image" src="https://user-images.githubusercontent.com/122367168/212650511-52c94131-9519-47d4-9360-4e64bcbebecc.png">

**Component(s) affected**
 Kingdom

**Version**
37bf941150cead85842b46d9726186ee52f316f3

**Environment**
Origin's Dev (v2a.dev-kingdom.isba.org.uk.) and Prod (Kingdom.originmediameasurement.com) Environments 

**Additional context**
Below screenshots belongs to Origin's Dev environment
 
<img width="922" alt="image" src="https://user-images.githubusercontent.com/122367168/212654114-ea293d96-1cbc-4c08-916c-906fa20a7702.png">

<img width="705" alt="image" src="https://user-images.githubusercontent.com/122367168/212654348-1dfb8b85-a94d-48ec-b455-66afc3195862.png">

- Please let us know for more details. Thank you.

**Comment by duliomatos1** [comment]
Thanks for opening, @dprao88. Can you share the version you are running (commit hash of the code you've built)?
(So we can rule out any previously fixed bug)

**Comment by tristanvuong2021** [comment]
I took a quick look and saw the bug in the code. I will fix this.
