### ISSUE TITLE
The mill has a memory issue

### ISSUE THREAD

**Issue by wangyaopw** [world-federation-of-advertisers/cross-media-measurement#86]
In theory, the mill's memory usage should be reset to ground level between processing two computations. However, when doing extensive performance test, I find the "non-evictable memory" usage of the mill keeps increasing as it processes more and more computations. It is unclear where these "non-evictable memory" comes from. Also the jvm maximum memory is set to 4GB, but the "non-evictable memory" usage can be way more than that, e.g. 10+GB.

![image](https://user-images.githubusercontent.com/64107318/120367361-ff2aa080-c2cd-11eb-9206-535721608e38.png)

We don't think there is any memory leakage in either the kotlin or c++ code.  But we need a deeper investigation on this issue at the appropriate time.

**Comment by wangyaopw** [comment]
There are more computation processing than the number of steps in the graph. So it is unlikely that the mill gather more "non-evictable memory" at each processing.

**Comment by renjiezh** [comment]
Fixed by https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1639
