### ISSUE TITLE
tech-debt : Replace service account authentication with workload identity.

### ISSUE THREAD

**Issue by wfa-siyengar** [world-federation-of-advertisers/cross-media-measurement#888]
**Describe the tech-debt**
We have employed service account authentication.
The best practice is to use the workload identity.

**Comment by SanjayVas** [comment]
Note that this is a hard requirement that should be addressed ASAP (i.e. revoking all service account keys ASAP).

**Comment by kungfucraig** [comment]
Here are some instructions.
https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions
