### ISSUE TITLE
Kingdom deployment is unsucessful without the spanner wipe

### ISSUE THREAD

**Issue by ana-angelico-accenture** [world-federation-of-advertisers/cross-media-measurement#903]
**Describe the bug**
The latest versions can not be deployed successfully without wiping the spanner database. The error appears on the Kingdom workload `gcp-kingdom-data-server-deployment`.

**Steps to reproduce**
1. Don't wipe the spanner database
2. Deploy KG with one of these versions

**Component(s) affected**
Kingdom 

**Version**

[`3af0f6a`](https://github.com/world-federation-of-advertisers/cross-media-measurement/commit/3af0f6a255f81cf3e8a0548fce223571689f234e) & [`ad6c66e`](https://github.com/world-federation-of-advertisers/cross-media-measurement/commit/ad6c66e81db4e4193bd3b72c832bded9d029e78f)

**Environment**
Origin dev & prd environment

**Additional context**
Logs:
"timestamp": "2023-03-17T15:38:59.617279909Z"
"textPayload": "liquibase.exception.ValidationFailedException: Validation Failed:",
"timestamp": "2023-03-17T15:38:59.645187642Z",
"textPayload": "     1 changesets check sum",
"timestamp": "2023-03-17T15:38:59.645238604Z"
"textPayload": "          kingdom/spanner/create-measurement-schema.sql::1::sanjayvas was: 8:f77777df0d5c78c4e8dfc3fdc25ab6b9 but is now: 8:b5acfd3137959e38e032173937b9061d",

Complete Logs:
    "textPayload": "Mar 17, 2023 3:38:59 PM liquibase.lockservice",
    "insertId": "rixw1e0lnljf43af",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "container_name": "update-kingdom-schema",
        "namespace_name": "default",
        "location": "europe-west2",
        "pod_name": "gcp-kingdom-data-server-deployment-59cc776b7f-zh56g",
        
        "cluster_name": "origin-kg-env-k8s-cluster"
      }
    },
    "timestamp": "2023-03-17T15:38:59.617230919Z",
    "severity": "ERROR",
    "labels": {
      "compute.googleapis.com/resource_name": "gke-origin-kg-env--origin-kg-env--0044c598-bje9",
      "k8s-pod/app": "gcp-kingdom-data-server-app",
      "k8s-pod/pod-template-hash": "59cc776b7f"
    },
    "logName": "/logs/stderr",
    "receiveTimestamp": "2023-03-17T15:39:03.036738733Z"
  },
  {
    "textPayload": "INFO: Successfully released change log lock",
    "insertId": "pvwf5oq1ws47mirv",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "location": "europe-west2",
        "pod_name": "gcp-kingdom-data-server-deployment-59cc776b7f-zh56g",
        "cluster_name": "origin-kg-env-k8s-cluster",
        "namespace_name": "default",
        "container_name": "update-kingdom-schema"
      }
    },
    "timestamp": "2023-03-17T15:38:59.617279909Z",
    "severity": "ERROR",
    "labels": {
      "k8s-pod/app": "gcp-kingdom-data-server-app",
      "compute.googleapis.com/resource_name": "gke-origin-kg-env--origin-kg-env--0044c598-bje9",
      "k8s-pod/pod-template-hash": "59cc776b7f"
    },
    "logName": "/logs/stderr",
    "receiveTimestamp": "2023-03-17T15:39:03.036738733Z"
  },
  {
    "textPayload": "liquibase.exception.ValidationFailedException: Validation Failed:",
    "insertId": "0p17ufqf27iv0xux",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "namespace_name": "default",
        "pod_name": "gcp-kingdom-data-server-deployment-59cc776b7f-zh56g",
        "location": "europe-west2",
        "cluster_name": "origin-kg-env-k8s-cluster",
        
        "container_name": "update-kingdom-schema"
      }
    },
    "timestamp": "2023-03-17T15:38:59.645187642Z",
    "severity": "ERROR",
    "labels": {
      "k8s-pod/pod-template-hash": "59cc776b7f",
      "compute.googleapis.com/resource_name": "gke-origin-kg-env--origin-kg-env--0044c598-bje9",
      "k8s-pod/app": "gcp-kingdom-data-server-app"
    },
    "logName": "/logs/stderr",
    "receiveTimestamp": "2023-03-17T15:39:03.036738733Z"
  },
  {
    "textPayload": "     1 changesets check sum",
    "insertId": "8hq2mrk0e8rum3gz",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "cluster_name": "origin-kg-env-k8s-cluster",
        "location": "europe-west2",
        "namespace_name": "default",
        "pod_name": "gcp-kingdom-data-server-deployment-59cc776b7f-zh56g",
        
        "container_name": "update-kingdom-schema"
      }
    },
    "timestamp": "2023-03-17T15:38:59.645238604Z",
    "severity": "ERROR",
    "labels": {
      "compute.googleapis.com/resource_name": "gke-origin-kg-env--origin-kg-env--0044c598-bje9",
      "k8s-pod/app": "gcp-kingdom-data-server-app",
      "k8s-pod/pod-template-hash": "59cc776b7f"
    },
    "logName": "/logs/stderr",
    "receiveTimestamp": "2023-03-17T15:39:03.036738733Z"
  },
  {
    "textPayload": "          kingdom/spanner/create-measurement-schema.sql::1::sanjayvas was: 8:f77777df0d5c78c4e8dfc3fdc25ab6b9 but is now: 8:b5acfd3137959e38e032173937b9061d",
    "insertId": "6jm6fvfm8e5p7spb",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "cluster_name": "origin-kg-env-k8s-cluster",
        "namespace_name": "default",
        "container_name": "update-kingdom-schema",
        "pod_name": "gcp-kingdom-data-server-deployment-59cc776b7f-zh56g",
        
        "location": "europe-west2"
      }
    },

**Comment by SanjayVas** [comment]
The primary error appears to be `liquibase.exception.ValidationFailedException: Validation Failed` for ID `kingdom/spanner/create-measurement-schema.sql::1::sanjayvas`. It looks like the issue was introduced in #864. Apparently comments factor into the changeset hash.
