### ISSUE TITLE
Direct requisition fulfilment uses unary method rather than stream

### ISSUE THREAD

**Issue by mariolamassaavedra** [world-federation-of-advertisers/cross-media-measurement#938]
**Describe the bug**
The direct fulfilment requisition method uses a single payload approach vs MPC fulfilment where the sketch is sent in chunks using steam method. This limitation is blocking single EDP direct fulfilment when the amount of data exceeds 4MBs

**Steps to reproduce**
1. Create measurement request for a single EDP requiring direct fulfilment
2. Reply to the requisition with a payload larger than 4MBs
3. EDP receives "CANCELLED" error and Kingdom logs RESOURCE_EXHAUSTED message

**Component(s) affected**
Kingdom

**Version**
7c63b7aa666c256d6304730aad788e18accdffe1

**Environment**
Origin Test Environment

**Additional context**
TV EDP is trying to fulfil a single EDP requisition for all adults for a specific campaign - the requisition samples 7,252,188 VIDs  resulting in more than 4MB worth of data 

<img width="982" alt="Screenshot 2023-04-11 at 16 30 38" src="https://user-images.githubusercontent.com/61779113/231213390-2c9cb18f-ebf3-43b5-a4e0-f639934c4393.png">

**Comment by SanjayVas** [comment]
Direct fulfillment is for single Measurement results, not sketches. The value should be very small and easily fit in the 4 MiB limit. This is working as intended.
