### ISSUE TITLE
Using tink key pairs error - no enabled keys found

### ISSUE THREAD

**Issue by MargaridaFaria23** [world-federation-of-advertisers/cross-media-measurement#939]
**Describe the bug**
No error when creating MC, just when using it
While trying to use the tink key pairs created using following Halo's instructions, we get a message saying that there are no enabled keys

**Steps to MC creation process**
1. Create account
     - using CreateResource tool we create a new account and retrieve the new account activation token and account name
2. Generate MC Creation Token
     - using the CreateResource tool we generate a MC Creation Token
3. Activate account
     - using the MeasurementSystem tool we authenticate the account, in which we retrieve a token which we use to activate the account
4. create MC
     - using same tool from last step, MeasurementSystem tool, we create the Measurement consumer
5. Create API Key
    - We use a grpcurl command with protos and certs required
6. Sign certificates etc...

**Component(s) affected**
Kingdom

**Version**
Commit - 7c63b7aa666c256d6304730aad788e18accdffe1

**Environment**
Origin-dev environment & Origin-test environment

**Additional context**
We are creating the tink key pairs following Halo's instuctions, but when we try to use them we get an error saying that there are no keys enabled

Logs: 
![image](https://user-images.githubusercontent.com/113896653/231251059-024cf1fd-d13b-452b-a020-ea4dcde2e219.png)

**Comment by MargaridaFaria23** [comment]
@SanjayVas just updated the issue with more context and a log with the error message.

**Comment by mariolamassaavedra** [comment]
@SanjayVas the error is not coming directly from the Kingdom itself. We have created the tink keys and created MCs as per the guides. Then when trying to encrypt metadata to create event groups first we fetch the MC's data by doing getMeasurementConsumers call, grab the public key and proceed to encrypt. At this points the tink library is throwing the error on the screenshot above about not having an enabled key. 

On slack you helped me validate one of the keys which happened to be Halo's, it seems the ones we have created are the ones having the issue, hence I am assuming we didn't create them correctly, but we followed the tink creation guide - hence why we are following up on this topic

**Comment by SanjayVas** [comment]
> the error is not coming directly from the Kingdom itself. We have created the tink keys and created MCs as per the guides. Then when trying to encrypt metadata to create event groups first we fetch the MC's data by doing getMeasurementConsumers call, grab the public key and proceed to encrypt. At this points the tink library is throwing the error on the screenshot above about not having an enabled key.

I assumed this was the case. I was trying to indicate that the bug filing process was not being followed with the appropriate information.

I suspect that this is not a Halo issue given that the correctness test and manual usage in the dev/QA environment works. I suspect this is an issue either with generating/serializing the key for CreateMeasurementConsumer or with deserializing the key at the other end. Hence why the first thing I'd like to see is the `GetMeasurementConsumer` response so I can see if the key format is correct.

**Comment by mariolamassaavedra** [comment]
@SanjayVas here's a document with the gRPCurl call response, our code that calls the getMeasurementConsumer method and the response we get back from our grpc client
[PublicKey.docx](https://github.com/world-federation-of-advertisers/cross-media-measurement/files/11222564/PublicKey.docx)

**Comment by SanjayVas** [comment]
Decoding the public key data gives the following EncryptionPublicKey message:

```textproto
format: TINK_KEYSET
data: "\010\202\236\233\304\004\022\334\001\n\317\001\n=type.googleapis.com/google.crypto.tink.EciesAeadHkdfPublicKey\022\213\001\022D\n\004\010\002\020\003\022:\0228\n0type.googleapis.com/google.crypto.tink.AesGcmKey\022\002\020\020\030\001\030\001\032!\000\266\375\257=?\226\n\344zD\202O\250\277?\301Yd\034\231\010\351\230\212\336\235\312\372@d\364$\" \034\005n\345\227\343\263\257d\021\221T\314\034>\212\0228\204W\321Z\261S\336\212,Z\253\300U\255\030\003\020\001\030\202\236\233\304\004 \001"
```

Decoding this `data` field as a Tink Keyset message gives:

```
primary_key_id: 1216794370
key {
  key_data {
    type_url: "type.googleapis.com/google.crypto.tink.EciesAeadHkdfPublicKey"
    value: "\022D\n\004\010\002\020\003\022:\0228\n0type.googleapis.com/google.crypto.tink.AesGcmKey\022\002\020\020\030\001\030\001\032!\000\266\375\257=?\226\n\344zD\202O\250\277?\301Yd\034\231\010\351\230\212\336\235\312\372@d\364$\" \034\005n\345\227\343\263\257d\021\221T\314\034>\212\0228\204W\321Z\261S\336\212,Z\253\300U\255"
    key_material_type: ASYMMETRIC_PUBLIC
  }
  status: ENABLED
  key_id: 1216794370
  output_prefix_type: TINK
}
```

There is indeed a key with status `ENABLED` here. I suspect something is off in the code that deserializes the Tink Keyset and calls the Tink library. I assume you're not using the [consent-signaling-client](https://github.com/world-federation-of-advertisers/consent-signaling-client) library and have written your own code to do this. I don't see any problems in the Halo code here as it appears to have no issues passing the key through, so this issue can be considered closed.

If you separately share your code, I can see about helping debug that.
